name: Keep Repo Alive
on:
  schedule:
    - cron: "0 0 * * *"   # 每天运行一次
permissions:
  contents: write
jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
        with:
          use_api: false
          time_elapsed: 50
          commit_message: "🚧 keepalive: auto‑commit"
          committer_username: "my-bot"
          committer_email: "bot@example.com"
