name: Keep Repo Alive
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */25 * *'
permissions:
  contents: write
jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # 使用你创建的 PAT 进行 checkout
          token: ${{ secrets.PAT }}
      - uses: gautamkrishnar/keepalive-workflow@v2
        with:
          # 注意：当使用 PAT 时，通常不需要再指定 committer 的用户名和邮箱
          use_api: false
          time_elapsed: 25
          commit_message: "🚧 keepalive: auto-commit"
